"""autogenerated by genpy from project_simulation/bin_loc.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class bin_loc(genpy.Message):
  _md5sum = "5a1e584c103fee9bb86c3a78d3bc4869"
  _type = "project_simulation/bin_loc"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """std_msgs/UInt8 bin_id
std_msgs/String location
================================================================================
MSG: std_msgs/UInt8
uint8 data

================================================================================
MSG: std_msgs/String
string data

"""
  __slots__ = ['bin_id','location']
  _slot_types = ['std_msgs/UInt8','std_msgs/String']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       bin_id,location

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(bin_loc, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.bin_id is None:
        self.bin_id = std_msgs.msg.UInt8()
      if self.location is None:
        self.location = std_msgs.msg.String()
    else:
      self.bin_id = std_msgs.msg.UInt8()
      self.location = std_msgs.msg.String()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_B.pack(self.bin_id.data))
      _x = self.location.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.bin_id is None:
        self.bin_id = std_msgs.msg.UInt8()
      if self.location is None:
        self.location = std_msgs.msg.String()
      end = 0
      start = end
      end += 1
      (self.bin_id.data,) = _struct_B.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.location.data = str[start:end].decode('utf-8')
      else:
        self.location.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_B.pack(self.bin_id.data))
      _x = self.location.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.bin_id is None:
        self.bin_id = std_msgs.msg.UInt8()
      if self.location is None:
        self.location = std_msgs.msg.String()
      end = 0
      start = end
      end += 1
      (self.bin_id.data,) = _struct_B.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.location.data = str[start:end].decode('utf-8')
      else:
        self.location.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
