/* Auto-generated by genmsg_cpp for file /home/shray/groovy_workspace/sandbox/project_simulation/msg/AlvarMarker.msg */
#ifndef PROJECT_SIMULATION_MESSAGE_ALVARMARKER_H
#define PROJECT_SIMULATION_MESSAGE_ALVARMARKER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/PoseStamped.h"

namespace project_simulation
{
template <class ContainerAllocator>
struct AlvarMarker_ {
  typedef AlvarMarker_<ContainerAllocator> Type;

  AlvarMarker_()
  : header()
  , id(0)
  , pose()
  {
  }

  AlvarMarker_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , id(0)
  , pose(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint32_t _id_type;
  uint32_t id;

  typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
   ::geometry_msgs::PoseStamped_<ContainerAllocator>  pose;


  typedef boost::shared_ptr< ::project_simulation::AlvarMarker_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project_simulation::AlvarMarker_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct AlvarMarker
typedef  ::project_simulation::AlvarMarker_<std::allocator<void> > AlvarMarker;

typedef boost::shared_ptr< ::project_simulation::AlvarMarker> AlvarMarkerPtr;
typedef boost::shared_ptr< ::project_simulation::AlvarMarker const> AlvarMarkerConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::project_simulation::AlvarMarker_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::project_simulation::AlvarMarker_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace project_simulation

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::project_simulation::AlvarMarker_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::project_simulation::AlvarMarker_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::project_simulation::AlvarMarker_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7b611310a2363bd431e43a9c309dbb1e";
  }

  static const char* value(const  ::project_simulation::AlvarMarker_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7b611310a2363bd4ULL;
  static const uint64_t static_value2 = 0x31e43a9c309dbb1eULL;
};

template<class ContainerAllocator>
struct DataType< ::project_simulation::AlvarMarker_<ContainerAllocator> > {
  static const char* value() 
  {
    return "project_simulation/AlvarMarker";
  }

  static const char* value(const  ::project_simulation::AlvarMarker_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::project_simulation::AlvarMarker_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint32 id\n\
geometry_msgs/PoseStamped pose\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::project_simulation::AlvarMarker_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::project_simulation::AlvarMarker_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::project_simulation::AlvarMarker_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::project_simulation::AlvarMarker_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.id);
    stream.next(m.pose);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AlvarMarker_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project_simulation::AlvarMarker_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::project_simulation::AlvarMarker_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "pose: ";
s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PROJECT_SIMULATION_MESSAGE_ALVARMARKER_H

